services:
  - type: web
    name: meta-betties-frontend
    env: node
    buildCommand: |
      echo "=== Starting Clean Build Process ==="
      npm cache clean --force
      npm cache verify
      rm -rf node_modules package-lock.json
      rm -rf ~/.npm
      echo "=== Installing Dependencies ==="
      npm install --no-package-lock --legacy-peer-deps
      echo "=== Installing Mobile Adapter ==="
      npm install @solana-mobile/wallet-adapter-mobile@1.0.1 --save --no-package-lock --legacy-peer-deps
      echo "=== Installing Cross-env ==="
      npm install cross-env --save --no-package-lock --legacy-peer-deps
      echo "=== Building Application ==="
      npm run build:render
    startCommand: npm start
    envVars:
      - key: REACT_APP_API_URL
        value: https://api-server-wcjc.onrender.com
      - key: NODE_VERSION
        value: "18.17.0"
      - key: NPM_CONFIG_CACHE
        value: "/tmp/.npm"
    healthCheckPath: /
    autoDeploy: true 